"""
Django settings for opentamilweb project.

Generated by 'django-admin startproject' using Django 1.10.8.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os
import secrets
from django.utils.translation import gettext_lazy as _
from environs import Env
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent
env = Env()
env.read_env()
# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
#BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY',secrets.token_hex(48))
APP_KEY = SECRET_KEY.upper()

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG',not False)

ALLOWED_HOSTS = ["*",".tamilpesu.us"]
CSRF_TRUSTED_ORIGINS = ['tamilpesu.us',]

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "opentamilapp",
    "vennila"
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "opentamilweb.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.template.context_processors.i18n",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "opentamilweb.wsgi.application"

# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases

DEPLOY=not True

if DEPLOY:
    DATABASES = {
        "default":
        env.dj_db_url("DATABASE_URL", default="postgres://postgres@db/postgres")
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': 'sqlite',
        }
    }
    
# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/
# Provide a lists of languages which your site supports.
LANGUAGES = (
    ("en", _("English")),
    ("ta", _("Tamil")),
)
# Tell Django where the project's translation files should be.
LOCALE_PATHS = (os.path.join(BASE_DIR, "locale"),)
LANGUAGE_CODE = "ta"

TIME_ZONE = "UTC"

USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/

STATIC_URL = "/static/"
STATICFILES_DIRS = ["static"]
STATIC_ROOT = BASE_DIR / "opentamilap"
STATICFILES_STORAGE = "django.contrib.staticfiles.storage.StaticFilesStorage"

TEXTRANDOMIZER_FILES = []
# can be 'open-tamil.herokuapp.com' or 'tamilpesu.us' etc.
#CURRDIR = os.path.dirname(os.path.abspath(__file__))
APPDIR = BASE_DIR #os.path.dirname(CURRDIR)
EXAMPLE_SITE_URL = "tamilpesu.us"
CONTACT_EMAIL = "ezhillang@gmail.com"
print(BASE_DIR)
STATIC_ROOT = os.path.join(APPDIR,'opentamilapp','static')
